// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhzejfikcjhkobtfccia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpoemVqZmlrY2poa29idGZjY2lhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MjM5MzQsImV4cCI6MjA1ODk5OTkzNH0.wDl5Tz3-O-jR3TnYPqCmB6fQNDz2A8ZNMY1EkuMgV64";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);